#!/usr/bin/env php
<?php

use Maslosoft\AddendumI18NExtractor\Application\Application;

date_default_timezone_set('UTC');

$cwd = getcwd();

// Try existing autoloader first
$loaders = [
	$cwd . '/vendor/autoload.php',
	__DIR__ . '/vendor/autoload.php',
	__DIR__ . '/../../autoload.php'
];

foreach ($loaders as $path)
{
	if (file_exists($path))
	{
		require_once($path);
		break;
	}
}

$app = new Application;
$app->run();
