#!/usr/bin/env php
<?php

use Maslosoft\AddendumI18NExtractor\Application\Application;
use Maslosoft\AddendumI18NExtractor\I18NExtractor;

date_default_timezone_set('UTC');

if (file_exists(__DIR__ . '/vendor/autoload.php'))
{
	require_once(__DIR__ . '/vendor/autoload.php');
}
elseif (file_exists(__DIR__ . '/../../autoload.php'))
{
	require_once __DIR__ . '/../../autoload.php';
}

$app = new Application(new I18NExtractor());
$app->run();
